In [8]:
import collections
import math
import torch
from torch import nn
from d2l import torch as d2l

def sequence_mask(X, valid_len, value = 0):
    maxlen = X.size(1)
    mask = torch.arange((maxlen), dtype=torch.float32, device = X.device)[None, :] < valid_len[:, None]
    X[~mask] = value
    return X

class MaskedSoftmaxCELoss(nn.CrossEntropyLoss):
    def forward(self, pred, label, valid_len):
        weights = torch.ones_like(label)
        weights = sequence_mask(weights, valid_len)
        self.reduction = 'none'
        unweighted_loss = super().forward(pred.permute(0, 2, 1), label)
        xx = unweighted_loss * weights
        print(xx)
        weighted_loss = xx.mean(dim = 1)
        print(weighted_loss)
        return weighted_loss
    
loss = MaskedSoftmaxCELoss()
loss(torch.ones(3,4,10), torch.ones((3,4), dtype=torch.long), torch.tensor([4,2,0]))


tensor([[2.3026, 2.3026, 2.3026, 2.3026],
        [2.3026, 2.3026, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])
tensor([2.3026, 1.1513, 0.0000])


tensor([2.3026, 1.1513, 0.0000])